<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="com.ait.qa34.LoginTests" tests="4" skipped="0" failures="1" errors="0" timestamp="2024-04-13T21:41:59" hostname="DESKTOP-QMEBHNC" time="53.67">
  <properties/>
  <testcase name="addNewUserPositiveTestFromDataProviderWithScvFile[0](NewUser{email='gsgs@gmai.com', password='Hgf435_s', firstName='Tatiana', lastName='Kartash', confirmPassword='Hgf435_s'})" classname="com.ait.qa34.LoginTests" time="2.012"/>
  <testcase name="addNewUserPositiveTestFromDataProviderWithScvFile[1](NewUser{email='sgsfa@gmail.com', password='Fgsgha45-6', firstName='Aleksey', lastName='Kartash', confirmPassword='Fgsgha45-6'})" classname="com.ait.qa34.LoginTests" time="1.97"/>
  <testcase name="addNewUserPositiveTestFromDataProviderWithScvFile[2](NewUser{email='sfffa@gmail.com', password='Ghjskds65!hss', firstName='Alena', lastName='Juk', confirmPassword='Fgsgha45-6'})" classname="com.ait.qa34.LoginTests" time="16.357">
    <failure message="java.lang.AssertionError: expected [true] but found [false]" type="java.lang.AssertionError">java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:111)
	at org.testng.Assert.failNotEquals(Assert.java:1578)
	at org.testng.Assert.assertTrue(Assert.java:57)
	at org.testng.Assert.assertTrue(Assert.java:67)
	at com.ait.qa34.LoginTests.addNewUserPositiveTestFromDataProviderWithScvFile(LoginTests.java:40)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.testng.TestRunner.privateRun(TestRunner.java:819)
	at org.testng.TestRunner.run(TestRunner.java:619)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
	at org.testng.SuiteRunner.run(SuiteRunner.java:336)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
	at org.testng.TestNG.runSuites(TestNG.java:1134)
	at org.testng.TestNG.run(TestNG.java:1101)
	at org.gradle.api.internal.tasks.testing.testng.TestNGTestClassProcessor.runTests(TestNGTestClassProcessor.java:145)
	at org.gradle.api.internal.tasks.testing.testng.TestNGTestClassProcessor.stop(TestNGTestClassProcessor.java:92)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:62)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy2.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$3.run(TestWorker.java:193)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:113)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:65)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
</failure>
  </testcase>
  <testcase name="addNewUserPositiveTestFromDataProviderWithScvFile[3](NewUser{email='dgsgdns@gmail.com', password='Fhdhsjs76_s', firstName='Dmitriy', lastName='Malikov', confirmPassword='Fhdhsjs76_s'})" classname="com.ait.qa34.LoginTests" time="1.859"/>
  <system-out><![CDATA[23:41:59.358 [Test worker] INFO  com.ait.qa34.TestBase -- Start test addNewUserPositiveTestFromDataProviderWithScvFilewith data:[NewUser{email='gsgs@gmai.com', password='Hgf435_s', firstName='Tatiana', lastName='Kartash', confirmPassword='Hgf435_s'}]
23:42:01.412 [Test worker] INFO  com.ait.qa34.TestBase -- PASSED addNewUserPositiveTestFromDataProviderWithScvFile
23:42:01.413 [Test worker] INFO  com.ait.qa34.TestBase -- Stop test
23:42:01.413 [Test worker] INFO  com.ait.qa34.TestBase -- =============================================
23:42:01.416 [Test worker] INFO  com.ait.qa34.TestBase -- Start test addNewUserPositiveTestFromDataProviderWithScvFilewith data:[NewUser{email='sgsfa@gmail.com', password='Fgsgha45-6', firstName='Aleksey', lastName='Kartash', confirmPassword='Fgsgha45-6'}]
23:42:18.919 [Test worker] INFO  com.ait.qa34.TestBase -- PASSED addNewUserPositiveTestFromDataProviderWithScvFile
23:42:18.920 [Test worker] INFO  com.ait.qa34.TestBase -- Stop test
23:42:18.920 [Test worker] INFO  com.ait.qa34.TestBase -- =============================================
23:42:18.926 [Test worker] INFO  com.ait.qa34.TestBase -- Start test addNewUserPositiveTestFromDataProviderWithScvFilewith data:[NewUser{email='sfffa@gmail.com', password='Ghjskds65!hss', firstName='Alena', lastName='Juk', confirmPassword='Fgsgha45-6'}]
23:42:51.188 [Test worker] ERROR com.ait.qa34.TestBase -- FAILED addNewUserPositiveTestFromDataProviderWithScvFileScreenshotC:\QA\QA34_FirstSeleniumProjectHW\screenshots\screen-1713044571173.png
23:42:51.188 [Test worker] INFO  com.ait.qa34.TestBase -- Stop test
23:42:51.188 [Test worker] INFO  com.ait.qa34.TestBase -- =============================================
23:42:51.188 [Test worker] INFO  com.ait.qa34.TestBase -- Start test addNewUserPositiveTestFromDataProviderWithScvFilewith data:[NewUser{email='dgsgdns@gmail.com', password='Fhdhsjs76_s', firstName='Dmitriy', lastName='Malikov', confirmPassword='Fhdhsjs76_s'}]
23:42:53.069 [Test worker] INFO  com.ait.qa34.TestBase -- PASSED addNewUserPositiveTestFromDataProviderWithScvFile
23:42:53.069 [Test worker] INFO  com.ait.qa34.TestBase -- Stop test
23:42:53.069 [Test worker] INFO  com.ait.qa34.TestBase -- =============================================
]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
